- name: yarn istall
  get_url: url="https://dl.yarnpkg.com/rpm/yarn.repo" dest=/etc/yum.repos.d/yarn.repo
- shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash
- yum: name={{item}} state=present
  with_items:
    - yarn
    - nodejs
- shell: npm i -g npm && npm cache clean -f && npm install -g n && n stable

