### creating users in list ###
- name: create users
  user: name={{item}} shell=/bin/bash state=present
  with_items: "{{users}}"
- file: path=/home/{{item}}/.ssh state=directory owner={{item}}
  with_items: "{{users}}"

### put user's keys in their home dirs ####
- template: src={{item}}-authorized_keys.j2 dest=/home/{{item}}/.ssh/authorized_keys mode=0700 owner={{item}}
  with_items: "{{users}}"

#### removes if not in list ####
#- name: removing if not in list
#  shell: "getent passwd | awk -F: '$3 > 1004 {print $1}'"
#  register: remove
#- user: name={{item}} state=absent remove=yes
#  with_items: "{{remove.stdout_lines}}"
#  when: item not in users

### sudo for specified users ###
- name: adding sudo rights
  template: src=sudo.j2 dest=/etc/sudoers.d/{{item}}
  with_items: "{{sudo}}"
